export type ExchangeProgram = {
  id: string; name: string; country: string; level: string; funding: string;
  benefits: string; gpa: string; language: string; deadline: string; link: string; linkLabel: string;
};

export type ScholarshipProgram = {
  id: string; name: string; country: string; level: string; category: string; link: string; linkLabel: string;
};

export const exchangePrograms: ExchangeProgram[] = [
  {
    "id": "ex-1",
    "name": "Pertukaran Mahasiswa / Kampus Merdeka",
    "country": "Indonesia",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://kampusmerdeka.kemdikbud.go.id/",
    "linkLabel": "Kampus Merdeka"
  },
  {
    "id": "ex-2",
    "name": "UI Student Exchange Program",
    "country": "Indonesia / Global",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://international.ui.ac.id/studex-opportunities/",
    "linkLabel": "UI International Office"
  },
  {
    "id": "ex-3",
    "name": "UI Global Mobility",
    "country": "Indonesia / Global",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://globalmobility.ui.ac.id/",
    "linkLabel": "UI Global Mobility"
  },
  {
    "id": "ex-4",
    "name": "Telkom University International Mobility",
    "country": "Indonesia / Global",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://exchange.telkomuniversity.ac.id/",
    "linkLabel": "Telkom Mobility"
  },
  {
    "id": "ex-5",
    "name": "UGM Student Mobility",
    "country": "Indonesia / Global",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://oia.ugm.ac.id/",
    "linkLabel": "UGM International"
  },
  {
    "id": "ex-6",
    "name": "ITB Student Exchange",
    "country": "Indonesia / Global",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://partnership.itb.ac.id/",
    "linkLabel": "ITB International Relations"
  },
  {
    "id": "ex-7",
    "name": "ITS Global Engagement – Student Exchange",
    "country": "Indonesia / Global",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://www.its.ac.id/international/",
    "linkLabel": "ITS Global Engagement"
  },
  {
    "id": "ex-8",
    "name": "UNAIR Student Exchange",
    "country": "Indonesia / Global",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://global.unair.ac.id/",
    "linkLabel": "UNAIR Global Engagement"
  },
  {
    "id": "ex-9",
    "name": "UNDIP International Mobility",
    "country": "Indonesia / Global",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://io.undip.ac.id/",
    "linkLabel": "UNDIP International Office"
  },
  {
    "id": "ex-10",
    "name": "IPB International Mobility",
    "country": "Indonesia / Global",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://global.ipb.ac.id/",
    "linkLabel": "IPB International"
  },
  {
    "id": "ex-11",
    "name": "AFS Intercultural Programs",
    "country": "Global",
    "level": "SMA",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://afs.org/",
    "linkLabel": "AFS"
  },
  {
    "id": "ex-12",
    "name": "Bina Antarbudaya / AFS Indonesia",
    "country": "Indonesia → Global",
    "level": "SMA",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://bina-antarbudaya.or.id/",
    "linkLabel": "Bina Antarbudaya"
  },
  {
    "id": "ex-13",
    "name": "Kennedy-Lugar YES Program",
    "country": "Amerika Serikat",
    "level": "SMA",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://www.yesprograms.org/",
    "linkLabel": "YES Programs"
  },
  {
    "id": "ex-14",
    "name": "YFU Student Exchange",
    "country": "Global",
    "level": "SMA",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://yfu.org/",
    "linkLabel": "YFU"
  },
  {
    "id": "ex-15",
    "name": "Rotary Youth Exchange",
    "country": "Global",
    "level": "SMA",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://www.rotary.org/en/our-programs/youth-exchanges",
    "linkLabel": "Rotary Youth Exchanges"
  },
  {
    "id": "ex-16",
    "name": "Global Undergraduate Exchange / Global UGRAD",
    "country": "AS",
    "level": "S1",
    "funding": "Fully funded / dukungan pendanaan (sesuai seleksi)",
    "benefits": "Tuition/biaya program, tiket atau tunjangan dapat tersedia; cek komponen resmi",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://www.worldlearning.org/program/global-undergraduate-exchange-program/",
    "linkLabel": "World Learning Global UGRAD"
  },
  {
    "id": "ex-17",
    "name": "Erasmus+ Student Mobility",
    "country": "Eropa",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://erasmus-plus.ec.europa.eu/opportunities/opportunities-for-individuals/students",
    "linkLabel": "Erasmus+ Students"
  },
  {
    "id": "ex-18",
    "name": "Erasmus+ International Credit Mobility",
    "country": "Eropa/Global",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://erasmus-plus.ec.europa.eu/",
    "linkLabel": "Erasmus+"
  },
  {
    "id": "ex-19",
    "name": "AIESEC Global Volunteer",
    "country": "Global",
    "level": "SMA/S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://aiesec.org/global-volunteer",
    "linkLabel": "AIESEC Global Volunteer"
  },
  {
    "id": "ex-20",
    "name": "AIESEC Global Talent",
    "country": "Global",
    "level": "SMA/S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://aiesec.org/global-talent",
    "linkLabel": "AIESEC Global Talent"
  },
  {
    "id": "ex-21",
    "name": "AIESEC Global Teacher",
    "country": "Global",
    "level": "SMA/S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://aiesec.org/global-teacher",
    "linkLabel": "AIESEC Global Teacher"
  },
  {
    "id": "ex-22",
    "name": "UMAP Student Exchange",
    "country": "Asia Pasifik",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://umap.org/",
    "linkLabel": "UMAP"
  },
  {
    "id": "ex-23",
    "name": "AIMS Programme",
    "country": "ASEAN/Asia",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://rihed.seameo.org/aims/",
    "linkLabel": "SEAMEO RIHED AIMS"
  },
  {
    "id": "ex-24",
    "name": "ASEAN University Network – AUN-ACTS",
    "country": "ASEAN",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://www.aunsec.org/",
    "linkLabel": "AUN"
  },
  {
    "id": "ex-25",
    "name": "JENESYS",
    "country": "Jepang/Asia Pasifik",
    "level": "SMA/S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://www.mofa.go.jp/",
    "linkLabel": "MOFA Japan JENESYS"
  },
  {
    "id": "ex-26",
    "name": "SSEAYP – Ship for Southeast Asian and Japanese Youth",
    "country": "ASEAN/Jepang",
    "level": "SMA/S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://www8.cao.go.jp/youth/kouryu/en/sseayp/sseayp.html",
    "linkLabel": "Cabinet Office Japan"
  },
  {
    "id": "ex-27",
    "name": "Ship for World Youth Program",
    "country": "Jepang/Global",
    "level": "SMA/S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://www8.cao.go.jp/youth/kouryu/en/",
    "linkLabel": "SWY Japan"
  },
  {
    "id": "ex-28",
    "name": "Sakura Science Exchange Program",
    "country": "Jepang",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://ssp.jst.go.jp/EN/",
    "linkLabel": "Sakura Science"
  },
  {
    "id": "ex-29",
    "name": "JASSO Student Exchange Support Program",
    "country": "Jepang",
    "level": "S1",
    "funding": "Fully funded / dukungan pendanaan (sesuai seleksi)",
    "benefits": "Tuition/biaya program, tiket atau tunjangan dapat tersedia; cek komponen resmi",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://www.jasso.go.jp/en/",
    "linkLabel": "JASSO"
  },
  {
    "id": "ex-30",
    "name": "GKS Exchange Students Program",
    "country": "Korea Selatan",
    "level": "S1",
    "funding": "Fully funded / dukungan pendanaan (sesuai seleksi)",
    "benefits": "Tuition/biaya program, tiket atau tunjangan dapat tersedia; cek komponen resmi",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://www.studyinkorea.go.kr/eng/plan/scholarship.do",
    "linkLabel": "Study in Korea – GKS Exchange"
  },
  {
    "id": "ex-31",
    "name": "CAMPUS Asia",
    "country": "Jepang–Korea–China/Asia",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://www.campusasia.jp/",
    "linkLabel": "CAMPUS Asia"
  },
  {
    "id": "ex-32",
    "name": "ISEP Student Exchange",
    "country": "Global",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://www.isepstudyabroad.org/",
    "linkLabel": "ISEP Study Abroad"
  },
  {
    "id": "ex-33",
    "name": "IAESTE International Internship Exchange",
    "country": "Global",
    "level": "SMA/S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://iaeste.org/",
    "linkLabel": "IAESTE"
  },
  {
    "id": "ex-34",
    "name": "IFMSA SCOPE Professional Exchange",
    "country": "Global / Kedokteran",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://ifmsa.org/standing-committees/professional-exchanges/",
    "linkLabel": "IFMSA SCOPE"
  },
  {
    "id": "ex-35",
    "name": "IFMSA SCORE Research Exchange",
    "country": "Global / Kedokteran",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://ifmsa.org/standing-committees/research-exchanges/",
    "linkLabel": "IFMSA SCORE"
  },
  {
    "id": "ex-36",
    "name": "Chiba University Student Exchange",
    "country": "Jepang",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://international.ui.ac.id/studex-chiba-spring27/",
    "linkLabel": "UI–Chiba Exchange 2027"
  },
  {
    "id": "ex-37",
    "name": "Kyoto University Student Exchange",
    "country": "Jepang",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://international.ui.ac.id/studex-kyoto-spring27/",
    "linkLabel": "UI–Kyoto Exchange 2027"
  },
  {
    "id": "ex-38",
    "name": "University of Tokyo Student Exchange",
    "country": "Jepang",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://www.u-tokyo.ac.jp/en/academics/ustep.html",
    "linkLabel": "University of Tokyo USTEP"
  },
  {
    "id": "ex-39",
    "name": "Waseda University Exchange",
    "country": "Jepang",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://www.waseda.jp/inst/cie/en/exchange",
    "linkLabel": "Waseda Exchange Programs"
  },
  {
    "id": "ex-40",
    "name": "Keio University Student Exchange",
    "country": "Jepang",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://www.ic.keio.ac.jp/en/study/exchange/",
    "linkLabel": "Keio International Exchange"
  },
  {
    "id": "ex-41",
    "name": "Tohoku University Exchange Programs",
    "country": "Jepang",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://www.insc.tohoku.ac.jp/english/exchange/",
    "linkLabel": "Tohoku University Exchange"
  },
  {
    "id": "ex-42",
    "name": "Sophia University Exchange Program",
    "country": "Jepang",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://piloti.sophia.ac.jp/eng/studyabroad/exchangeprograms/",
    "linkLabel": "Sophia Exchange"
  },
  {
    "id": "ex-43",
    "name": "Kanazawa University Exchange",
    "country": "Jepang",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://www.kanazawa-u.ac.jp/en/",
    "linkLabel": "Kanazawa International Exchange"
  },
  {
    "id": "ex-44",
    "name": "Kyushu University Exchange",
    "country": "Jepang",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://www.isc.kyushu-u.ac.jp/intlweb/en",
    "linkLabel": "Kyushu University International"
  },
  {
    "id": "ex-45",
    "name": "National University of Singapore Exchange",
    "country": "Singapura",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://www.nus.edu.sg/gro/global-programmes/student-exchange",
    "linkLabel": "NUS Global Relations"
  },
  {
    "id": "ex-46",
    "name": "Chulalongkorn University Exchange",
    "country": "Thailand",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://www.chula.ac.th/en/academics/exchange-student/",
    "linkLabel": "Chulalongkorn International Programs"
  },
  {
    "id": "ex-47",
    "name": "Universiti Malaya Student Exchange",
    "country": "Malaysia",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://gem.um.edu.my/",
    "linkLabel": "UM Global Mobility"
  },
  {
    "id": "ex-48",
    "name": "University of Queensland Exchange",
    "country": "Australia",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://study.uq.edu.au/study-options/study-abroad",
    "linkLabel": "UQ Study Abroad and Exchange"
  },
  {
    "id": "ex-49",
    "name": "University of Otago Student Exchange",
    "country": "Selandia Baru",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://www.otago.ac.nz/international/future-students/student-exchange",
    "linkLabel": "Otago Student Exchange"
  },
  {
    "id": "ex-50",
    "name": "HKUST Student Exchange",
    "country": "Hong Kong",
    "level": "S1",
    "funding": "Bervariasi sesuai skema program",
    "benefits": "Tuition, tiket, uang saku, dan asuransi mengikuti kebijakan penyelenggara",
    "gpa": "Mengikuti ketentuan penyelenggara atau kampus asal",
    "language": "Mengikuti negara tujuan dan ketentuan program",
    "deadline": "Berubah setiap intake — cek situs resmi",
    "link": "https://studyabroad.hkust.edu.hk/",
    "linkLabel": "HKUST Study Abroad"
  }
];

export const scholarshipPrograms: ScholarshipProgram[] = [
  {
    "id": "sch-n-1",
    "name": "LPDP Beasiswa Reguler",
    "country": "Indonesia",
    "level": "S2/S3",
    "category": "Beasiswa Nasional",
    "link": "https://lpdp.kemenkeu.go.id/",
    "linkLabel": "LPDP"
  },
  {
    "id": "sch-n-2",
    "name": "LPDP Perguruan Tinggi Utama Dunia",
    "country": "Indonesia",
    "level": "S2/S3",
    "category": "Beasiswa Nasional",
    "link": "https://lpdp.kemenkeu.go.id/",
    "linkLabel": "LPDP PTUD"
  },
  {
    "id": "sch-n-3",
    "name": "LPDP Beasiswa Parsial",
    "country": "Indonesia",
    "level": "S2/S3",
    "category": "Beasiswa Nasional",
    "link": "https://lpdp.kemenkeu.go.id/",
    "linkLabel": "LPDP"
  },
  {
    "id": "sch-n-4",
    "name": "LPDP Daerah Afirmasi",
    "country": "Indonesia",
    "level": "S2/S3",
    "category": "Beasiswa Nasional",
    "link": "https://lpdp.kemenkeu.go.id/",
    "linkLabel": "LPDP Afirmasi"
  },
  {
    "id": "sch-n-5",
    "name": "LPDP Prasejahtera",
    "country": "Indonesia",
    "level": "S2",
    "category": "Beasiswa Nasional",
    "link": "https://lpdp.kemenkeu.go.id/",
    "linkLabel": "LPDP Afirmasi"
  },
  {
    "id": "sch-n-6",
    "name": "LPDP Penyandang Disabilitas",
    "country": "Indonesia",
    "level": "S2/S3",
    "category": "Beasiswa Nasional",
    "link": "https://lpdp.kemenkeu.go.id/",
    "linkLabel": "LPDP Afirmasi"
  },
  {
    "id": "sch-n-7",
    "name": "LPDP Putra-Putri Papua",
    "country": "Indonesia",
    "level": "S2/S3",
    "category": "Beasiswa Nasional",
    "link": "https://lpdp.kemenkeu.go.id/",
    "linkLabel": "LPDP Afirmasi"
  },
  {
    "id": "sch-n-8",
    "name": "LPDP PNS/TNI/POLRI",
    "country": "Indonesia",
    "level": "S2/S3",
    "category": "Beasiswa Nasional",
    "link": "https://lpdp.kemenkeu.go.id/",
    "linkLabel": "LPDP Targeted"
  },
  {
    "id": "sch-n-9",
    "name": "LPDP Dokter Spesialis/Subspesialis",
    "country": "Indonesia",
    "level": "Profesi",
    "category": "Beasiswa Nasional",
    "link": "https://lpdp.kemenkeu.go.id/",
    "linkLabel": "LPDP"
  },
  {
    "id": "sch-n-10",
    "name": "Beasiswa Pendidikan Indonesia/BPI",
    "country": "Indonesia",
    "level": "S1–S3",
    "category": "Beasiswa Nasional",
    "link": "https://beasiswa.kemdikbud.go.id/",
    "linkLabel": "BPI Kemendikdasmen/Kemdiktisaintek"
  },
  {
    "id": "sch-n-11",
    "name": "Beasiswa Unggulan",
    "country": "Indonesia",
    "level": "S1/S2/S3",
    "category": "Beasiswa Nasional",
    "link": "https://beasiswaunggulan.kemdikbud.go.id/",
    "linkLabel": "Beasiswa Unggulan"
  },
  {
    "id": "sch-n-12",
    "name": "KIP Kuliah",
    "country": "Indonesia",
    "level": "D3/D4/S1",
    "category": "Beasiswa Nasional",
    "link": "https://kip-kuliah.kemdikbud.go.id/",
    "linkLabel": "KIP Kuliah"
  },
  {
    "id": "sch-n-13",
    "name": "Beasiswa Indonesia Bangkit",
    "country": "Indonesia",
    "level": "S1/S2/S3",
    "category": "Beasiswa Nasional",
    "link": "https://beasiswa.kemenag.go.id/",
    "linkLabel": "Beasiswa Indonesia Bangkit"
  },
  {
    "id": "sch-n-14",
    "name": "Beasiswa Bank Indonesia / GenBI",
    "country": "Indonesia",
    "level": "S1",
    "category": "Beasiswa Nasional",
    "link": "https://www.bi.go.id/",
    "linkLabel": "Bank Indonesia"
  },
  {
    "id": "sch-n-15",
    "name": "Djarum Beasiswa Plus",
    "country": "Indonesia",
    "level": "S1/D4",
    "category": "Beasiswa Nasional",
    "link": "https://djarumbeasiswaplus.org/",
    "linkLabel": "Djarum Beasiswa Plus"
  },
  {
    "id": "sch-n-16",
    "name": "Tanoto Foundation TELADAN",
    "country": "Indonesia",
    "level": "S1",
    "category": "Beasiswa Nasional",
    "link": "https://www.tanotofoundation.org/id/teladan/",
    "linkLabel": "Tanoto TELADAN"
  },
  {
    "id": "sch-n-17",
    "name": "Pertamina Sobat Bumi",
    "country": "Indonesia",
    "level": "S1",
    "category": "Beasiswa Nasional",
    "link": "https://pertaminafoundation.org/",
    "linkLabel": "Pertamina Foundation"
  },
  {
    "id": "sch-n-18",
    "name": "BAZNAS Beasiswa",
    "country": "Indonesia",
    "level": "S1 dan program tertentu",
    "category": "Beasiswa Nasional",
    "link": "https://beasiswa.baznas.go.id/",
    "linkLabel": "BAZNAS Beasiswa"
  },
  {
    "id": "sch-n-19",
    "name": "Bakti BCA Scholarship",
    "country": "Indonesia",
    "level": "S1",
    "category": "Beasiswa Nasional",
    "link": "https://www.bca.co.id/id/informasi/Edukatips/2024/05/22/09/50/beasiswa-bakti-bca",
    "linkLabel": "Bakti BCA"
  },
  {
    "id": "sch-n-20",
    "name": "BCA PPTI",
    "country": "Indonesia",
    "level": "Lulusan SMA/SMK",
    "category": "Beasiswa Nasional",
    "link": "https://karir.bca.co.id/",
    "linkLabel": "BCA Karier PPTI"
  },
  {
    "id": "sch-i-21",
    "name": "Australia Awards Scholarship",
    "country": "Australia",
    "level": "S2/S3",
    "category": "Beasiswa Internasional",
    "link": "https://www.australiaawardsindonesia.org/",
    "linkLabel": "Australia Awards Indonesia"
  },
  {
    "id": "sch-i-22",
    "name": "Chevening Scholarship",
    "country": "Inggris",
    "level": "S2",
    "category": "Beasiswa Internasional",
    "link": "https://www.chevening.org/scholarships/",
    "linkLabel": "Chevening"
  },
  {
    "id": "sch-i-23",
    "name": "Fulbright Scholarship",
    "country": "Amerika Serikat",
    "level": "S2/S3",
    "category": "Beasiswa Internasional",
    "link": "https://www.aminef.or.id/",
    "linkLabel": "AMINEF Fulbright Indonesia"
  },
  {
    "id": "sch-i-24",
    "name": "MEXT Undergraduate Scholarship",
    "country": "Jepang",
    "level": "S1",
    "category": "Beasiswa Internasional",
    "link": "https://www.studyinjapan.go.jp/en/planning/scholarships/mext-scholarships/",
    "linkLabel": "Study in Japan MEXT"
  },
  {
    "id": "sch-i-25",
    "name": "MEXT Research Student Scholarship",
    "country": "Jepang",
    "level": "S2/S3/Research",
    "category": "Beasiswa Internasional",
    "link": "https://www.studyinjapan.go.jp/en/planning/scholarships/mext-scholarships/",
    "linkLabel": "MEXT Scholarships"
  },
  {
    "id": "sch-i-26",
    "name": "Global Korea Scholarship – GKS Undergraduate",
    "country": "Korea",
    "level": "S1",
    "category": "Beasiswa Internasional",
    "link": "https://www.studyinkorea.go.kr/",
    "linkLabel": "GKS Undergraduate"
  },
  {
    "id": "sch-i-27",
    "name": "Global Korea Scholarship – GKS Graduate",
    "country": "Korea",
    "level": "S2/S3",
    "category": "Beasiswa Internasional",
    "link": "https://www.studyinkorea.go.kr/",
    "linkLabel": "GKS Graduate"
  },
  {
    "id": "sch-i-28",
    "name": "Erasmus Mundus Joint Masters",
    "country": "Eropa",
    "level": "S2",
    "category": "Beasiswa Internasional",
    "link": "https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en",
    "linkLabel": "Erasmus Mundus Catalogue"
  },
  {
    "id": "sch-i-29",
    "name": "DAAD EPOS",
    "country": "Jerman",
    "level": "S2/S3",
    "category": "Beasiswa Internasional",
    "link": "https://www.daad.de/en/studying-in-germany/scholarships/daad-scholarships/",
    "linkLabel": "DAAD Scholarship Database"
  },
  {
    "id": "sch-i-30",
    "name": "DAAD Study Scholarships",
    "country": "Jerman",
    "level": "S2",
    "category": "Beasiswa Internasional",
    "link": "https://www.daad.de/en/studying-in-germany/scholarships/",
    "linkLabel": "DAAD Scholarships"
  },
  {
    "id": "sch-i-31",
    "name": "Swedish Institute Scholarship for Global Professionals",
    "country": "Swedia",
    "level": "S2",
    "category": "Beasiswa Internasional",
    "link": "https://si.se/en/apply/scholarships/",
    "linkLabel": "SI Scholarships"
  },
  {
    "id": "sch-i-32",
    "name": "Eiffel Excellence Scholarship",
    "country": "Prancis",
    "level": "S2/S3",
    "category": "Beasiswa Internasional",
    "link": "https://www.campusfrance.org/en/eiffel-scholarship-program-of-excellence",
    "linkLabel": "Eiffel Scholarship"
  },
  {
    "id": "sch-i-33",
    "name": "Stipendium Hungaricum",
    "country": "Hungaria",
    "level": "S1/S2/S3",
    "category": "Beasiswa Internasional",
    "link": "https://stipendiumhungaricum.hu/",
    "linkLabel": "Stipendium Hungaricum"
  },
  {
    "id": "sch-i-34",
    "name": "Türkiye Scholarships",
    "country": "Turki",
    "level": "S1/S2/S3",
    "category": "Beasiswa Internasional",
    "link": "https://www.turkiyeburslari.gov.tr/",
    "linkLabel": "Türkiye Burslari"
  },
  {
    "id": "sch-i-35",
    "name": "Chinese Government Scholarship / CSC",
    "country": "China",
    "level": "S1/S2/S3",
    "category": "Beasiswa Internasional",
    "link": "https://www.campuschina.org/",
    "linkLabel": "Campus China CSC"
  },
  {
    "id": "sch-i-36",
    "name": "TaiwanICDF Scholarship",
    "country": "Taiwan",
    "level": "S1/S2/S3",
    "category": "Beasiswa Internasional",
    "link": "https://www.icdf.org.tw/wSite/ct?xItem=12505&ctNode=30316&mp=2",
    "linkLabel": "TaiwanICDF Scholarship"
  },
  {
    "id": "sch-i-37",
    "name": "Taiwan Scholarship – MOE",
    "country": "Taiwan",
    "level": "S1/S2/S3",
    "category": "Beasiswa Internasional",
    "link": "https://taiwanscholarship.moe.gov.tw/",
    "linkLabel": "Taiwan Scholarship"
  },
  {
    "id": "sch-i-38",
    "name": "Brunei Darussalam Government Scholarship",
    "country": "Brunei",
    "level": "Diploma/S1/S2",
    "category": "Beasiswa Internasional",
    "link": "https://www.mfa.gov.bn/Pages/online-bdgs.aspx",
    "linkLabel": "Brunei Government Scholarship"
  },
  {
    "id": "sch-i-39",
    "name": "Swiss Government Excellence Scholarships",
    "country": "Swiss",
    "level": "S3/Postdoc/Research",
    "category": "Beasiswa Internasional",
    "link": "https://www.sbfi.admin.ch/en/swiss-government-excellence-scholarships",
    "linkLabel": "Swiss Government Excellence Scholarships"
  },
  {
    "id": "sch-i-40",
    "name": "Gates Cambridge Scholarship",
    "country": "Inggris",
    "level": "S2/S3",
    "category": "Beasiswa Internasional",
    "link": "https://www.gatescambridge.org/",
    "linkLabel": "Gates Cambridge"
  },
  {
    "id": "sch-i-41",
    "name": "Clarendon Scholarship – Oxford",
    "country": "Inggris",
    "level": "S2/S3",
    "category": "Beasiswa Internasional",
    "link": "https://www.ox.ac.uk/clarendon",
    "linkLabel": "Clarendon Oxford"
  },
  {
    "id": "sch-i-42",
    "name": "Rhodes Scholarship",
    "country": "Oxford, UK",
    "level": "S2/S3",
    "category": "Beasiswa Internasional",
    "link": "https://www.rhodeshouse.ox.ac.uk/scholarships/",
    "linkLabel": "Rhodes Scholarships"
  },
  {
    "id": "sch-i-43",
    "name": "Knight-Hennessy Scholars",
    "country": "Stanford, AS",
    "level": "Graduate",
    "category": "Beasiswa Internasional",
    "link": "https://knight-hennessy.stanford.edu/",
    "linkLabel": "Knight-Hennessy"
  },
  {
    "id": "sch-i-44",
    "name": "Schwarzman Scholars",
    "country": "China",
    "level": "S2",
    "category": "Beasiswa Internasional",
    "link": "https://www.schwarzmanscholars.org/",
    "linkLabel": "Schwarzman Scholars"
  },
  {
    "id": "sch-i-45",
    "name": "Yenching Academy Scholarship",
    "country": "China",
    "level": "S2",
    "category": "Beasiswa Internasional",
    "link": "https://yenchingacademy.pku.edu.cn/",
    "linkLabel": "Yenching Academy"
  },
  {
    "id": "sch-i-46",
    "name": "ADB–Japan Scholarship Program",
    "country": "Asia/Jepang",
    "level": "S2",
    "category": "Beasiswa Internasional",
    "link": "https://www.adb.org/work-with-us/careers/japan-scholarship-program",
    "linkLabel": "ADB-JSP"
  },
  {
    "id": "sch-i-47",
    "name": "Joint Japan/World Bank Graduate Scholarship",
    "country": "Global",
    "level": "S2",
    "category": "Beasiswa Internasional",
    "link": "https://www.worldbank.org/en/programs/scholarships",
    "linkLabel": "JJ/WBGSP"
  },
  {
    "id": "sch-i-48",
    "name": "Islamic Development Bank Scholarship",
    "country": "Global",
    "level": "S1/S2/S3",
    "category": "Beasiswa Internasional",
    "link": "https://www.isdb.org/scholarships",
    "linkLabel": "IsDB Scholarships"
  },
  {
    "id": "sch-i-49",
    "name": "Commonwealth Master's Scholarships",
    "country": "Inggris",
    "level": "S2",
    "category": "Beasiswa Internasional",
    "link": "https://cscuk.fcdo.gov.uk/scholarships/",
    "linkLabel": "Commonwealth Scholarships"
  },
  {
    "id": "sch-i-50",
    "name": "Manaaki New Zealand Scholarships",
    "country": "Selandia Baru",
    "level": "S1/S2/S3 tergantung negara",
    "category": "Beasiswa Internasional",
    "link": "https://www.nzscholarships.govt.nz/",
    "linkLabel": "Manaaki Scholarships"
  }
];

